tolerations:
  - key: "role"
    operator: "Equal"
    value: "infra"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: In
              values:
                - infra