apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-ha-group
  namespace: longhorn-system
spec:
  cron: "0 */12 * * *"
  task: "backup"
  groups:
    - ha-backup
  retain: 3
  concurrency: 2
