apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot-group
  namespace: longhorn-system
spec:
  cron: "*/30 * * * *"
  task: "snapshot"
  groups:
    - s-ha-snap
  retain: 1
  concurrency: 2
