kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-semmi-ha
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  dataLocality: best-effort
  fromBackup: ""
  fsType: "ext4"
  migratable: "true"
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"